language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
script:
- chmod +x ./gradlew
- ./gradlew build
#- ./gradlew build connectedCheck  # TODO: Replace the previous line with this one when tests are required
